### ISSUE TITLE
PC Lags a lot for some seconds when game is closing.

### ISSUE THREAD

**Issue by NormanTS1** [vaporvee/discord-sdk-godot#46]
### What happened?

When i close the game and i have the plugin enabled, the pc starts lagging a lot, and then after some seconds, the game closes.

### Version

3.2

### Godot Version

4.2.stable

### Exact steps to reproduce this error

When i close the game and i have the plugin enabled, the pc starts lagging a lot, and then after some seconds, the game closes.

### GDScript

```gdscript
Doesn't have to do with the code.
```

### Godot output

```shell
Works normally.
```

### Additional information

Nothing.

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.

**Comment by vaporvee** [comment]
is already fixed but i broke linux support. i got sick so i didn't have time to fix it for release.

**Comment by NormanTS1** [comment]
Strange, it still happens to me, and i downloaded the 3.2 version of the plugin.

**Comment by NormanTS1** [comment]
(I'm on windows btw).

**Comment by vaporvee** [comment]
i just told you i didn't have time to fix stuff for releasing it

**Comment by NormanTS1** [comment]
Ohh yeah ok, my bad. I'll wait for the next release then, have a nice day!

**Comment by vaporvee** [comment]
no problem! i will remind you :)

**Comment by vaporvee** [comment]
got fixed but make sure to read the release nodes
